### ISSUE TITLE
Jobs are submitted succesfully, but only runs on head node

### ISSUE THREAD

**Issue by majorbytes** [HenrikBengtsson/future.batchtools#50]
I am trying to get the future.batchtools and doFuture to run on my Rocks 7 cluster, but it is only running the jobs on the head node.  I can see the submitted jobs and all of the allocations in sview, but nothing is running on the nodes..
Got any pointers?

**Comment by HenrikBengtsson** [comment]
FYI, I've transferred this issue from doFuture to future.batchtools since it's very unlikely it's related to doFuture.  It's more a future backend issue.

Also, I'll go ahead and close this issue since I think it's [batchtools](https://github.com/mllg/batchtools/) related, but feel free to reopen it if you think there's an issue with future.batchtools per se.
